In [ ]:
pip install pandas openpyxl xlwings

In [ ]:
import numpy as np
import pandas as pd
from statsmodels.stats.inter_rater import fleiss_kappa
from statsmodels.stats.inter_rater import aggregate_raters
import openpyxl

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving Classification of the results.xlsx to Classification of the results.xlsx


In [ ]:
file = pd.read_excel('Classification of the results.xlsx', sheet_name='LLM Review Score')
file

,LLM,Prompting Strategies,Name of the System,Review Criterion,Run,Score given by the LLM
0,GPT4o,Zero Shot,Baidu Apollo,Argument Comprehension,1,2.0
1,GPT4o,Zero Shot,Baidu Apollo,Argument Comprehension,2,2.0
2,GPT4o,Zero Shot,Baidu Apollo,Argument Comprehension,3,2.0
3,GPT4o,Zero Shot,Baidu Apollo,Argument Comprehension,4,2.0
4,GPT4o,Zero Shot,Baidu Apollo,Argument Comprehension,5,2.0
...,...,...,...,...,...,...
955,Gemini 2.0 Flash,CoT One Shot,Lane Management System,Argument Criticism and Defeat,1,3.0
956,Gemini 2.0 Flash,CoT One Shot,Lane Management System,Argument Criticism and Defeat,2,3.0
957,Gemini 2.0 Flash,CoT One Shot,Lane Management System,Argument Criticism and Defeat,3,3.0
958,Gemini 2.0 Flash,CoT One Shot,Lane Management System,Argument Criticism and Defeat,4,3.0


In [ ]:
argument_comprehension = file.loc[file['Review Criterion'] == 'Argument Comprehension']
ZS_AC = argument_comprehension.loc[argument_comprehension['Prompting Strategies'] == 'Zero Shot']

ZS_AC_4o = ZS_AC.loc[ZS_AC['LLM'] == 'GPT4o']
ZS_AC_4o = ZS_AC_4o.drop(columns=['Review Criterion', 'Run', 'LLM', 'Prompting Strategies', 'Name of the System'])
ZS_AC_4o = ZS_AC_4o.to_numpy().reshape(20, 1)
#print(ZS_AC_4o)
#print(ZS_AC_4o.shape)

ZS_AC_4point1 = ZS_AC.loc[ZS_AC['LLM'] == 'GPT4.1']
ZS_AC_4point1 = ZS_AC_4point1.drop(columns=['Review Criterion', 'Run', 'LLM', 'Prompting Strategies', 'Name of the System'])
ZS_AC_4point1 = ZS_AC_4point1.to_numpy().reshape(20,1)
#print(ZS_AC_4point1)
#print(ZS_AC_4point1.shape)

ZS_AC_Deepseek = ZS_AC.loc[ZS_AC['LLM'] == 'Deepseek Reasoner']
ZS_AC_Deepseek = ZS_AC_Deepseek.drop(columns=['Review Criterion', 'Run', 'LLM', 'Prompting Strategies', 'Name of the System'])
ZS_AC_Deepseek = ZS_AC_Deepseek.to_numpy().reshape(20,1)
#print(ZS_AC_Deepseek)
#print(ZS_AC_Deepseek.shape)

ZS_AC_Gemini = ZS_AC.loc[ZS_AC['LLM'] == 'Gemini 2.0 Flash']
ZS_AC_Gemini = ZS_AC_Gemini.drop(columns=['Review Criterion', 'Run', 'LLM', 'Prompting Strategies', 'Name of the System'])
ZS_AC_Gemini = ZS_AC_Gemini.to_numpy().reshape(20,1)
#print(ZS_AC_Gemini)
#print(ZS_AC_Gemini.shape)

ZS_AC_aggregate = np.concatenate((ZS_AC_4o, ZS_AC_4point1, ZS_AC_Deepseek, ZS_AC_Gemini), axis = 1)
ZS_AC_aggregate = ZS_AC_aggregate.astype(int)
ZS_AC_aggregate = ZS_AC_aggregate - 1
#Aggregates are subtracted by 1 since aggregate_raters start from 0 and our ratings start at 1

aggregated_ZS_AC, categories= aggregate_raters(ZS_AC_aggregate, n_cat=5)
print(aggregated_ZS_AC)

fleiss_kappa_ZS_AC = fleiss_kappa(aggregated_ZS_AC, method="fleiss")
print("Fleiss Kappa: " ,fleiss_kappa_ZS_AC)

[[0 2 2 0 0]
 [0 2 2 0 0]
 [0 2 2 0 0]
 [0 2 2 0 0]
 [0 2 2 0 0]
 [0 0 3 1 0]
 [0 1 2 1 0]
 [0 0 3 1 0]
 [0 1 2 1 0]
 [0 1 2 1 0]
 [0 0 1 3 0]
 [0 0 3 1 0]
 [0 0 2 2 0]
 [0 0 2 2 0]
 [0 0 3 1 0]
 [0 1 3 0 0]
 [0 1 2 1 0]
 [0 1 3 0 0]
 [0 2 1 1 0]
 [0 1 3 0 0]]
Fleiss Kappa:  -0.09277984743657978


Well-Formedness for Zero Shot

In [ ]:
WellFormedness = file.loc[file['Review Criterion'] == 'Well-Formedness(Syntax)'] #filters out review criterions that are not Well-Formedness(Syntax)
ZS_WF = WellFormedness.loc[WellFormedness['Prompting Strategies'] == 'Zero Shot'] #filters out non zero shot prompting strategy in WellFormedness


ZS_WF_4o = ZS_WF.loc[ZS_WF['LLM'] == 'GPT4o']
ZS_WF_4o = ZS_WF_4o.drop(columns=['Review Criterion', 'Run', 'LLM', 'Prompting Strategies', 'Name of the System'])
ZS_WF_4o = ZS_WF_4o.to_numpy().reshape(20, 1)

ZS_WF_4point1 = ZS_WF.loc[ZS_WF['LLM'] == 'GPT4.1']
ZS_WF_4point1 = ZS_WF_4point1.drop(columns=['Review Criterion', 'Run', 'LLM', 'Prompting Strategies', 'Name of the System'])
ZS_WF_4point1 = ZS_WF_4point1.to_numpy().reshape(20, 1)

ZS_WF_Deepseek = ZS_WF.loc[ZS_WF['LLM'] == 'Deepseek Reasoner']
ZS_WF_Deepseek = ZS_WF_Deepseek.drop(columns=['Review Criterion', 'Run', 'LLM', 'Prompting Strategies', 'Name of the System'])
ZS_WF_Deepseek = ZS_WF_Deepseek.to_numpy().reshape(20, 1)

ZS_WF_Gemini = ZS_WF.loc[ZS_WF['LLM'] == 'Gemini 2.0 Flash']
ZS_WF_Gemini = ZS_WF_Gemini.drop(columns=['Review Criterion', 'Run', 'LLM', 'Prompting Strategies', 'Name of the System'])
ZS_WF_Gemini = ZS_WF_Gemini.to_numpy().reshape(20, 1)

ZS_WF_aggregate = np.concatenate((ZS_WF_4o, ZS_WF_4point1, ZS_WF_Deepseek, ZS_WF_Gemini), axis = 1)
ZS_WF_aggregate = ZS_WF_aggregate.astype(int)
ZS_WF_aggregate = ZS_WF_aggregate - 1
#Aggregates are subtracted by 1 since aggregate_raters start from 0 and our ratings start at 1


aggregated_ZS_WF, categories = aggregate_raters(ZS_WF_aggregate, n_cat=5)
print(aggregated_ZS_WF)
fleiss_kappa_ZS_WF = fleiss_kappa(aggregated_ZS_WF, method='fleiss')
print("Fleiss Kappa: " ,fleiss_kappa_ZS_WF)

[[0 3 1 0 0]
 [1 1 2 0 0]
 [0 2 2 0 0]
 [2 2 0 0 0]
 [1 2 1 0 0]
 [0 0 3 1 0]
 [0 0 3 1 0]
 [0 0 3 1 0]
 [0 0 2 2 0]
 [0 0 3 1 0]
 [0 0 4 0 0]
 [0 0 4 0 0]
 [0 0 3 1 0]
 [0 0 4 0 0]
 [0 0 3 1 0]
 [0 0 3 1 0]
 [0 0 3 1 0]
 [0 0 3 1 0]
 [0 0 3 1 0]
 [0 1 2 1 0]]
Fleiss Kappa:  0.05604719764011765


Zero Shot Expressive Sufficiency

In [ ]:
ExpressiveSufficiency = file.loc[file['Review Criterion'] == 'Expressive Sufficiency ']
#print(ExpressiveSufficiency)
#file['Review Criterion'].unique()
ZS_ES = ExpressiveSufficiency.loc[ExpressiveSufficiency['Prompting Strategies'] == 'Zero Shot']
#print(ZS_ES)



ZS_ES_4o = ZS_ES.loc[ZS_ES['LLM'] == 'GPT4o']
ZS_ES_4o = ZS_ES_4o.drop(columns=['LLM', 'Prompting Strategies', 'Name of the System', 'Review Criterion', 'Run'])
ZS_ES_4o = ZS_ES_4o.to_numpy().reshape(20, 1)

ZS_ES_4point1 = ZS_ES.loc[ZS_ES['LLM'] == 'GPT4.1']
ZS_ES_4point1 = ZS_ES_4point1.drop(columns=['LLM', 'Prompting Strategies', 'Name of the System', 'Review Criterion', 'Run'])
ZS_ES_4point1 = ZS_ES_4point1.to_numpy().reshape(20, 1)

ZS_ES_Deepseek = ZS_ES.loc[ZS_ES['LLM'] == 'Deepseek Reasoner']
ZS_ES_Deepseek = ZS_ES_Deepseek.drop(columns=['LLM', 'Prompting Strategies', 'Name of the System', 'Review Criterion', 'Run'])
ZS_ES_Deepseek = ZS_ES_Deepseek.to_numpy().reshape(20, 1)

ZS_ES_Gemini = ZS_ES.loc[ZS_ES['LLM'] == 'Gemini 2.0 Flash']
ZS_ES_Gemini = ZS_ES_Gemini.drop(columns=['LLM', 'Prompting Strategies', 'Name of the System', 'Review Criterion', 'Run'])
ZS_ES_Gemini = ZS_ES_Gemini.to_numpy().reshape(20, 1)

ZS_ES_aggregate = np.concatenate((ZS_ES_4o, ZS_ES_4point1, ZS_ES_Deepseek, ZS_ES_Gemini), axis = 1)
ZS_ES_aggregate = ZS_ES_aggregate.astype(int)
#print(ZS_ES_aggregate)

ZS_ES_aggregate = ZS_ES_aggregate - 1
#Aggregates are subtracted by 1 since aggregate_raters start from 0 and our ratings start at 1
#print(ZS_ES_aggregate)

aggregated_ZS_ES, categories = aggregate_raters(ZS_ES_aggregate, n_cat=5)
#print(aggregated_ZS_ES)
fleiss_kappa_ZS_ES = fleiss_kappa(aggregated_ZS_ES, method='fleiss')
print("Fleiss Kappa: " ,fleiss_kappa_ZS_ES)


Fleiss Kappa:  -0.1615847334577888


Zero Shot Argument Criticism and Defeat

In [ ]:
ArgumentCriticism = file.loc[file['Review Criterion'] == 'Argument Criticism and Defeat']
ZS_AC_Defeat = ArgumentCriticism.loc[ArgumentCriticism['Prompting Strategies'] == 'Zero Shot']
#print(ZS_AC_Defeat)

ZS_AC_Defeat_4o = ZS_AC_Defeat.loc[ZS_AC_Defeat['LLM'] == 'GPT4o']
ZS_AC_Defeat_4o = ZS_AC_Defeat_4o.drop(columns=['LLM', 'Prompting Strategies', 'Name of the System', 'Review Criterion', 'Run'])
ZS_AC_Defeat_4o = ZS_AC_Defeat_4o.to_numpy().reshape(20, 1)

ZS_AC_Defeat_4point1 = ZS_AC_Defeat.loc[ZS_AC_Defeat['LLM'] == 'GPT4.1']
ZS_AC_Defeat_4point1 = ZS_AC_Defeat_4point1.drop(columns=['LLM', 'Prompting Strategies', 'Name of the System', 'Review Criterion', 'Run'])
ZS_AC_Defeat_4point1 = ZS_AC_Defeat_4point1.to_numpy().reshape(20, 1)

ZS_AC_Defeat_Deepseek = ZS_AC_Defeat.loc[ZS_AC_Defeat['LLM'] == 'Deepseek Reasoner']
ZS_AC_Defeat_Deepseek = ZS_AC_Defeat_Deepseek.drop(columns=['LLM', 'Prompting Strategies', 'Name of the System', 'Review Criterion', 'Run'])
ZS_AC_Defeat_Deepseek = ZS_AC_Defeat_Deepseek.to_numpy().reshape(20, 1)

ZS_AC_Defeat_Gemini = ZS_AC_Defeat.loc[ZS_AC_Defeat['LLM'] == 'Gemini 2.0 Flash']
ZS_AC_Defeat_Gemini = ZS_AC_Defeat_Gemini.drop(columns=['LLM', 'Prompting Strategies', 'Name of the System', 'Review Criterion', 'Run'])
ZS_AC_Defeat_Gemini = ZS_AC_Defeat_Gemini.to_numpy().reshape(20, 1)

ZS_AC_Defeat_aggregate = np.concatenate((ZS_AC_Defeat_4o, ZS_AC_Defeat_4point1, ZS_AC_Defeat_Deepseek, ZS_AC_Defeat_Gemini), axis = 1)
ZS_AC_Defeat_aggregate = ZS_AC_Defeat_aggregate.astype(int)
#print(ZS_AC_Defeat_aggregate)

ZS_AC_Defeat_aggregate = ZS_AC_Defeat_aggregate - 1
#Aggregates are subtracted by 1 since aggregate_raters start from 0 and our ratings start at 1
#print(ZS_AC_Defeat_aggregate)

aggregated_ZS_AC_Defeat, categories = aggregate_raters(ZS_AC_Defeat_aggregate, n_cat=5)
print(aggregated_ZS_AC_Defeat)

fleiss_kappa_ZS_AC_Defeat = fleiss_kappa(aggregated_ZS_AC_Defeat, method='fleiss')
print("Fleiss Kappa: ", fleiss_kappa_ZS_AC_Defeat)

[[0 1 3 0 0]
 [0 2 2 0 0]
 [0 1 3 0 0]
 [0 1 2 1 0]
 [0 1 3 0 0]
 [0 0 3 1 0]
 [0 0 3 1 0]
 [0 0 2 2 0]
 [0 0 2 2 0]
 [0 0 2 2 0]
 [0 0 3 1 0]
 [0 0 3 1 0]
 [0 0 3 1 0]
 [0 0 2 2 0]
 [0 0 3 1 0]
 [0 1 3 0 0]
 [0 0 3 1 0]
 [0 0 3 1 0]
 [0 0 3 1 0]
 [0 1 3 0 0]]
Fleiss Kappa:  -0.15417743324720107


CoT Zero Shot

CoT Zero Shot Argument Comprehension

In [ ]:
CoT_ZS_AC = argument_comprehension.loc[argument_comprehension['Prompting Strategies'] == 'CoT Zero Shot']


CoT_ZS_AC_4o = CoT_ZS_AC.loc[CoT_ZS_AC['LLM'] == 'GPT4o']
CoT_ZS_AC_4o = CoT_ZS_AC_4o.drop(columns=['LLM', 'Prompting Strategies', 'Name of the System', 'Review Criterion', 'Run'])
CoT_ZS_AC_4o = CoT_ZS_AC_4o.to_numpy().reshape(20, 1)

CoT_ZS_AC_4point1 = CoT_ZS_AC.loc[CoT_ZS_AC['LLM'] == 'GPT4.1']
CoT_ZS_AC_4point1 = CoT_ZS_AC_4point1.drop(columns=['LLM', 'Prompting Strategies', 'Name of the System', 'Review Criterion', 'Run'])
CoT_ZS_AC_4point1 = CoT_ZS_AC_4point1.to_numpy().reshape(20, 1)

CoT_ZS_AC_Deepseek = CoT_ZS_AC.loc[CoT_ZS_AC['LLM'] == 'Deepseek Reasoner']
CoT_ZS_AC_Deepseek = CoT_ZS_AC_Deepseek.drop(columns=['LLM', 'Prompting Strategies', 'Name of the System', 'Review Criterion', 'Run'])
CoT_ZS_AC_Deepseek = CoT_ZS_AC_Deepseek.to_numpy().reshape(20, 1)

CoT_ZS_AC_Gemini = CoT_ZS_AC.loc[CoT_ZS_AC['LLM'] == 'Gemini 2.0 Flash']
CoT_ZS_AC_Gemini = CoT_ZS_AC_Gemini.drop(columns=['LLM', 'Prompting Strategies', 'Name of the System', 'Review Criterion', 'Run'])
CoT_ZS_AC_Gemini = CoT_ZS_AC_Gemini.to_numpy().reshape(20, 1)

CoT_ZS_AC_aggregate = np.concatenate((CoT_ZS_AC_4o, CoT_ZS_AC_4point1, CoT_ZS_AC_Deepseek, CoT_ZS_AC_Gemini), axis = 1)
CoT_ZS_AC_aggregate = CoT_ZS_AC_aggregate.astype(int)
CoT_ZS_AC_aggregate = CoT_ZS_AC_aggregate - 1
#Aggregates are subtracted by 1 since aggregate_raters start from 0 and our ratings start at 1

aggregated_CoT_ZS_AC, categories = aggregate_raters(CoT_ZS_AC_aggregate, n_cat=5)
print(aggregated_CoT_ZS_AC)

fleiss_kappa_CoT_ZS_AC = fleiss_kappa(aggregated_CoT_ZS_AC, method='fleiss')
print("Fleiss Kappa: ", fleiss_kappa_CoT_ZS_AC)

[[0 0 4 0 0]
 [0 1 3 0 0]
 [0 1 3 0 0]
 [0 1 3 0 0]
 [0 1 3 0 0]
 [0 0 2 2 0]
 [0 0 2 1 1]
 [0 0 2 2 0]
 [0 0 2 2 0]
 [0 0 3 1 0]
 [0 0 2 2 0]
 [0 0 3 1 0]
 [0 0 0 4 0]
 [0 0 2 2 0]
 [0 0 1 3 0]
 [0 0 3 1 0]
 [0 0 4 0 0]
 [0 0 3 1 0]
 [0 0 2 2 0]
 [0 0 3 1 0]]
Fleiss Kappa:  0.03417229384080202


CoT Zero Shot Well-Formedness

In [ ]:
CoT_ZS_WF = WellFormedness.loc[WellFormedness['Prompting Strategies'] == 'CoT Zero Shot']


CoT_ZS_WF_4o = CoT_ZS_WF.loc[CoT_ZS_WF['LLM'] == 'GPT4o']
CoT_ZS_WF_4o = CoT_ZS_WF_4o.drop(columns=['LLM', 'Prompting Strategies', 'Name of the System', 'Review Criterion', 'Run'])
CoT_ZS_WF_4o = CoT_ZS_WF_4o.to_numpy().reshape(20, 1)

CoT_ZS_WF_4point1 = CoT_ZS_WF.loc[CoT_ZS_WF['LLM'] == 'GPT4.1']
CoT_ZS_WF_4point1 = CoT_ZS_WF_4point1.drop(columns=['LLM', 'Prompting Strategies', 'Name of the System', 'Review Criterion', 'Run'])
CoT_ZS_WF_4point1 = CoT_ZS_WF_4point1.to_numpy().reshape(20, 1)

CoT_ZS_WF_Deepseek = CoT_ZS_WF.loc[CoT_ZS_WF['LLM'] == 'Deepseek Reasoner']
CoT_ZS_WF_Deepseek = CoT_ZS_WF_Deepseek.drop(columns=['LLM', 'Prompting Strategies', 'Name of the System', 'Review Criterion', 'Run'])
CoT_ZS_WF_Deepseek = CoT_ZS_WF_Deepseek.to_numpy().reshape(20, 1)

CoT_ZS_WF_Gemini = CoT_ZS_WF.loc[CoT_ZS_WF['LLM'] == 'Gemini 2.0 Flash']
CoT_ZS_WF_Gemini = CoT_ZS_WF_Gemini.drop(columns=['LLM', 'Prompting Strategies', 'Name of the System', 'Review Criterion', 'Run'])
#print(CoT_ZS_WF_Gemini)
CoT_ZS_WF_Gemini = CoT_ZS_WF_Gemini.to_numpy().reshape(20, 1)

CoT_ZS_WF_aggregate = np.concatenate((CoT_ZS_WF_4o, CoT_ZS_WF_4point1, CoT_ZS_WF_Deepseek, CoT_ZS_WF_Gemini), axis = 1)
CoT_ZS_WF_aggregate = CoT_ZS_WF_aggregate.astype(int)
#print(CoT_ZS_WF_aggregate)
CoT_ZS_WF_aggregate = CoT_ZS_WF_aggregate - 1
#Aggregates are subtracted by 1 since aggregate_raters start from 0 and our ratings start at 1
#print(CoT_ZS_WF_aggregate)

aggregated_CoT_ZS_WF, categories = aggregate_raters(CoT_ZS_WF_aggregate, n_cat=5)
print(aggregated_CoT_ZS_WF)

fleiss_kappa_CoT_ZS_WF = fleiss_kappa(aggregated_CoT_ZS_WF, method='fleiss')
print("Fleiss Kappa: ", fleiss_kappa_CoT_ZS_WF)

[[2 0 2 0 0]
 [1 1 2 0 0]
 [2 0 1 1 0]
 [2 0 2 0 0]
 [1 1 2 0 0]
 [0 0 0 4 0]
 [0 0 2 2 0]
 [0 0 2 2 0]
 [0 0 1 3 0]
 [0 0 1 3 0]
 [0 0 2 2 0]
 [0 0 2 2 0]
 [0 0 3 1 0]
 [0 0 3 1 0]
 [0 0 2 2 0]
 [0 0 2 2 0]
 [0 0 2 2 0]
 [0 0 2 2 0]
 [0 0 3 1 0]
 [0 0 2 2 0]]
Fleiss Kappa:  -0.02139406487232587


CoT Zero Shot Expressive Sufficiency

In [ ]:
CoT_ZS_ES = ExpressiveSufficiency.loc[ExpressiveSufficiency['Prompting Strategies'] == 'CoT Zero Shot']


CoT_ZS_ES_4o = CoT_ZS_ES.loc[CoT_ZS_ES['LLM'] == 'GPT4o']
CoT_ZS_ES_4o = CoT_ZS_ES_4o.drop(columns=['LLM', 'Prompting Strategies', 'Name of the System', 'Review Criterion', 'Run'])
CoT_ZS_ES_4o = CoT_ZS_ES_4o.to_numpy().reshape(20, 1)
#print(CoT_ZS_ES_4o)

CoT_ZS_ES_4point1 = CoT_ZS_ES.loc[CoT_ZS_ES['LLM'] == 'GPT4.1']
CoT_ZS_ES_4point1 = CoT_ZS_ES_4point1.drop(columns=['LLM', 'Prompting Strategies', 'Name of the System', 'Review Criterion', 'Run'])
CoT_ZS_ES_4point1 = CoT_ZS_ES_4point1.to_numpy().reshape(20, 1)

CoT_ZS_ES_Deepseek = CoT_ZS_ES.loc[CoT_ZS_ES['LLM'] == 'Deepseek Reasoner']
CoT_ZS_ES_Deepseek = CoT_ZS_ES_Deepseek.drop(columns=['LLM', 'Prompting Strategies', 'Name of the System', 'Review Criterion', 'Run'])
CoT_ZS_ES_Deepseek = CoT_ZS_ES_Deepseek.to_numpy().reshape(20, 1)

CoT_ZS_ES_Gemini = CoT_ZS_ES.loc[CoT_ZS_ES['LLM'] == 'Gemini 2.0 Flash']
CoT_ZS_ES_Gemini = CoT_ZS_ES_Gemini.drop(columns=['LLM', 'Prompting Strategies', 'Name of the System', 'Review Criterion', 'Run'])
CoT_ZS_ES_Gemini = CoT_ZS_ES_Gemini.to_numpy().reshape(20, 1)

CoT_ZS_ES_aggregate = np.concatenate((CoT_ZS_ES_4o, CoT_ZS_ES_4point1, CoT_ZS_ES_Deepseek, CoT_ZS_ES_Gemini), axis = 1)
CoT_ZS_ES_aggregate = CoT_ZS_ES_aggregate.astype(int)
CoT_ZS_ES_aggregate = CoT_ZS_ES_aggregate - 1
#Aggregates are subtracted by 1 since aggregate_raters start from 0 and our ratings start at 1

aggregated_CoT_ZS_ES, categories = aggregate_raters(CoT_ZS_ES_aggregate, n_cat=5)
print(aggregated_CoT_ZS_ES)

fleiss_kappa_CoT_ZS_ES = fleiss_kappa(aggregated_CoT_ZS_ES, method='fleiss')
print("Fleiss Kappa: ", fleiss_kappa_CoT_ZS_ES)


[[0 1 3 0 0]
 [0 1 2 1 0]
 [0 1 2 1 0]
 [0 1 3 0 0]
 [0 1 3 0 0]
 [0 0 3 1 0]
 [0 0 2 2 0]
 [0 0 2 2 0]
 [0 0 1 3 0]
 [0 0 1 3 0]
 [0 0 1 3 0]
 [0 0 3 0 1]
 [0 0 1 3 0]
 [0 0 1 3 0]
 [0 0 1 2 1]
 [0 0 1 3 0]
 [0 0 2 2 0]
 [0 0 2 2 0]
 [0 0 1 3 0]
 [0 0 2 2 0]]
Fleiss Kappa:  -0.02176650476704448


CoT Zero Shot Argument Criticism and Defeat

In [ ]:
CoT_ZS_AC_Defeat = ArgumentCriticism.loc[ArgumentCriticism['Prompting Strategies'] == 'CoT Zero Shot']
#print(CoT_ZS_AC_Defeat)


CoT_ZS_AC_Defeat_4o = CoT_ZS_AC_Defeat.loc[CoT_ZS_AC_Defeat['LLM'] == 'GPT4o']
CoT_ZS_AC_Defeat_4o = CoT_ZS_AC_Defeat_4o.drop(columns=['LLM', 'Prompting Strategies', 'Name of the System', 'Review Criterion', 'Run'])
CoT_ZS_AC_Defeat_4o = CoT_ZS_AC_Defeat_4o.to_numpy().reshape(20,1)

CoT_ZS_AC_Defeat_4point1 = CoT_ZS_AC_Defeat.loc[CoT_ZS_AC_Defeat['LLM'] == 'GPT4.1']
#print(CoT_ZS_AC_Defeat_4point1)
CoT_ZS_AC_Defeat_4point1 = CoT_ZS_AC_Defeat_4point1.drop(columns=['LLM', 'Prompting Strategies', 'Name of the System', 'Review Criterion', 'Run'])
#print(CoT_ZS_AC_Defeat_4point1)
CoT_ZS_AC_Defeat_4point1 = CoT_ZS_AC_Defeat_4point1.to_numpy().reshape(20, 1)

CoT_ZS_AC_Defeat_Deepseek = CoT_ZS_AC_Defeat.loc[CoT_ZS_AC_Defeat['LLM'] == 'Deepseek Reasoner']
CoT_ZS_AC_Defeat_Deepseek = CoT_ZS_AC_Defeat_Deepseek.drop(columns=['LLM', 'Prompting Strategies', 'Name of the System', 'Review Criterion', 'Run'])
CoT_ZS_AC_Defeat_Deepseek = CoT_ZS_AC_Defeat_Deepseek.to_numpy().reshape(20, 1)

CoT_ZS_AC_Defeat_Gemini = CoT_ZS_AC_Defeat.loc[CoT_ZS_AC_Defeat['LLM'] == 'Gemini 2.0 Flash']
CoT_ZS_AC_Defeat_Gemini = CoT_ZS_AC_Defeat_Gemini.drop(columns=['LLM', 'Prompting Strategies', 'Name of the System', 'Review Criterion', 'Run'])
CoT_ZS_AC_Defeat_Gemini = CoT_ZS_AC_Defeat_Gemini.to_numpy().reshape(20, 1)

CoT_ZS_AC_Defeat_aggregate = np.concatenate((CoT_ZS_AC_Defeat_4o, CoT_ZS_AC_Defeat_4point1, CoT_ZS_AC_Defeat_Deepseek, CoT_ZS_AC_Defeat_Gemini), axis = 1)
CoT_ZS_AC_Defeat_aggregate = CoT_ZS_AC_Defeat_aggregate.astype(int)
CoT_ZS_AC_Defeat_aggregate = CoT_ZS_AC_Defeat_aggregate - 1
#Aggregates are subtracted by 1 since aggregate_raters start from 0 and our ratings start at 1


aggregated_CoT_ZS_AC_Defeat, categories = aggregate_raters(CoT_ZS_AC_Defeat_aggregate, n_cat=5)
print(aggregated_CoT_ZS_AC_Defeat)

fleiss_kappa_CoT_ZS_AC_Defeat = fleiss_kappa(aggregated_CoT_ZS_AC_Defeat, method='fleiss')
print("Fleiss Kappa: ", fleiss_kappa_CoT_ZS_AC_Defeat)

[[0 0 4 0 0]
 [0 1 3 0 0]
 [0 1 3 0 0]
 [0 1 2 1 0]
 [0 0 4 0 0]
 [0 0 2 2 0]
 [0 0 3 1 0]
 [0 0 3 1 0]
 [0 0 3 1 0]
 [0 0 3 1 0]
 [0 0 2 2 0]
 [0 0 1 3 0]
 [0 0 2 2 0]
 [0 0 2 2 0]
 [0 0 1 3 0]
 [0 0 3 1 0]
 [0 1 2 1 0]
 [0 0 4 0 0]
 [0 0 3 1 0]
 [0 0 4 0 0]]
Fleiss Kappa:  -0.0008936550491511675


CoT One Shot

CoT One Shot Argument Comprehension

In [ ]:
CoT_OS_AC = argument_comprehension.loc[argument_comprehension['Prompting Strategies'] == 'CoT One Shot']


CoT_OS_AC_4o = CoT_OS_AC.loc[CoT_OS_AC['LLM'] == 'GPT4o']
CoT_OS_AC_4o = CoT_OS_AC_4o.drop(columns=['LLM', 'Prompting Strategies', 'Name of the System', 'Review Criterion', 'Run'])
CoT_OS_AC_4o = CoT_OS_AC_4o.to_numpy().reshape(20, 1)

CoT_OS_AC_4point1 = CoT_OS_AC.loc[CoT_OS_AC['LLM'] == 'GPT4.1']
CoT_OS_AC_4point1 = CoT_OS_AC_4point1.drop(columns=['LLM', 'Prompting Strategies', 'Name of the System', 'Review Criterion', 'Run'])
CoT_OS_AC_4point1 = CoT_OS_AC_4point1.to_numpy().reshape(20, 1)

CoT_OS_AC_Deepseek = CoT_OS_AC.loc[CoT_OS_AC['LLM'] == 'Deepseek Reasoner']
CoT_OS_AC_Deepseek = CoT_OS_AC_Deepseek.drop(columns=['LLM', 'Prompting Strategies', 'Name of the System', 'Review Criterion', 'Run'])
CoT_OS_AC_Deepseek = CoT_OS_AC_Deepseek.to_numpy().reshape(20, 1)

CoT_OS_AC_Gemini = CoT_OS_AC.loc[CoT_OS_AC['LLM'] == 'Gemini 2.0 Flash']
CoT_OS_AC_Gemini = CoT_OS_AC_Gemini.drop(columns=['LLM', 'Prompting Strategies', 'Name of the System', 'Review Criterion', 'Run'])
CoT_OS_AC_Gemini = CoT_OS_AC_Gemini.to_numpy().reshape(20, 1)

CoT_OS_AC_aggregate = np.concatenate((CoT_OS_AC_4o, CoT_OS_AC_4point1, CoT_OS_AC_Deepseek, CoT_OS_AC_Gemini), axis = 1)
CoT_OS_AC_aggregate = CoT_OS_AC_aggregate.astype(int)
CoT_OS_AC_aggregate = CoT_OS_AC_aggregate - 1
#Aggregates are subtracted by 1 since aggregate_raters start from 0 and our ratings start at 1

aggregated_CoT_OS_AC, categories = aggregate_raters(CoT_OS_AC_aggregate, n_cat=5)
print(aggregated_CoT_OS_AC)

fleiss_kappa_CoT_OS_AC = fleiss_kappa(aggregated_CoT_OS_AC, method='fleiss')
print("Fleiss Kappa: ", fleiss_kappa_CoT_OS_AC)

[[0 2 2 0 0]
 [0 2 2 0 0]
 [0 3 1 0 0]
 [0 1 3 0 0]
 [1 1 2 0 0]
 [0 0 1 3 0]
 [0 0 3 1 0]
 [0 0 3 1 0]
 [0 0 3 1 0]
 [0 0 3 1 0]
 [0 0 2 2 0]
 [0 0 2 2 0]
 [0 0 2 2 0]
 [0 0 2 2 0]
 [0 0 3 1 0]
 [0 0 3 1 0]
 [0 0 3 1 0]
 [0 0 3 1 0]
 [0 0 3 1 0]
 [0 0 3 1 0]]
Fleiss Kappa:  -0.04334484081319549


CoT One Shot Well-Formedness

In [ ]:
CoT_OS_WF = WellFormedness.loc[WellFormedness['Prompting Strategies'] == 'CoT One Shot']
#print(CoT_OS_WF)

CoT_OS_WF_4o = CoT_OS_WF.loc[CoT_OS_WF['LLM'] == 'GPT4o']
CoT_OS_WF_4o = CoT_OS_WF_4o.drop(columns=['LLM', 'Prompting Strategies', 'Name of the System', 'Review Criterion', 'Run'])
CoT_OS_WF_4o = CoT_OS_WF_4o.to_numpy().reshape(20, 1)
#print(CoT_OS_WF_4o)

CoT_OS_WF_4point1 = CoT_OS_WF.loc[CoT_OS_WF['LLM'] == 'GPT4.1']
CoT_OS_WF_4point1 = CoT_OS_WF_4point1.drop(columns=['LLM', 'Prompting Strategies', 'Name of the System', 'Review Criterion', 'Run'])
CoT_OS_WF_4point1 = CoT_OS_WF_4point1.to_numpy().reshape(20, 1)

CoT_OS_WF_Deepseek = CoT_OS_WF.loc[CoT_OS_WF['LLM'] == 'Deepseek Reasoner']
CoT_OS_WF_Deepseek = CoT_OS_WF_Deepseek.drop(columns=['LLM', 'Prompting Strategies', 'Name of the System', 'Review Criterion', 'Run'])
CoT_OS_WF_Deepseek = CoT_OS_WF_Deepseek.to_numpy().reshape(20, 1)

CoT_OS_WF_Gemini = CoT_OS_WF.loc[CoT_OS_WF['LLM'] == 'Gemini 2.0 Flash']
CoT_OS_WF_Gemini = CoT_OS_WF_Gemini.drop(columns=['LLM', 'Prompting Strategies', 'Name of the System', 'Review Criterion', 'Run'])
CoT_OS_WF_Gemini = CoT_OS_WF_Gemini.to_numpy().reshape(20, 1)
#print(CoT_OS_WF_Gemini)

CoT_OS_WF_aggregate = np.concatenate((CoT_OS_WF_4o, CoT_OS_WF_4point1, CoT_OS_WF_Deepseek, CoT_OS_WF_Gemini), axis = 1)
CoT_OS_WF_aggregate = CoT_OS_WF_aggregate.astype(int)
CoT_OS_WF_aggregate = CoT_OS_WF_aggregate - 1
#Aggregates are subtracted by 1 since aggregate_raters start from 0 and our ratings start at 1

aggregated_CoT_OS_WF, categories = aggregate_raters(CoT_OS_WF_aggregate, n_cat=5)
print(aggregated_CoT_OS_WF)

fleiss_kappa_CoT_OS_WF = fleiss_kappa(aggregated_CoT_OS_WF, method='fleiss')
print("Fleiss Kappa: ", fleiss_kappa_CoT_OS_WF)

[[1 1 2 0 0]
 [1 0 3 0 0]
 [1 1 2 0 0]
 [0 1 3 0 0]
 [1 0 3 0 0]
 [0 0 4 0 0]
 [0 0 4 0 0]
 [0 0 2 2 0]
 [0 0 3 1 0]
 [0 0 2 2 0]
 [0 0 3 1 0]
 [0 0 2 2 0]
 [0 0 4 0 0]
 [0 0 3 1 0]
 [0 0 3 1 0]
 [0 0 2 2 0]
 [0 0 2 2 0]
 [0 0 3 1 0]
 [0 0 3 1 0]
 [0 0 2 2 0]]
Fleiss Kappa:  -0.07512667988543732


CoT One Shot Expressive Sufficiency

In [ ]:
CoT_OS_ES = ExpressiveSufficiency.loc[ExpressiveSufficiency['Prompting Strategies'] == 'CoT One Shot']
#print(CoT_OS_ES)

CoT_OS_ES_4o = CoT_OS_ES.loc[CoT_OS_ES['LLM'] == 'GPT4o']
CoT_OS_ES_4o = CoT_OS_ES_4o.drop(columns=['LLM', 'Prompting Strategies', 'Name of the System', 'Review Criterion', 'Run'])
CoT_OS_ES_4o = CoT_OS_ES_4o.to_numpy().reshape(20, 1)

CoT_OS_ES_4point1 = CoT_OS_ES.loc[CoT_OS_ES['LLM'] == 'GPT4.1']
CoT_OS_ES_4point1 = CoT_OS_ES_4point1.drop(columns=['LLM', 'Prompting Strategies', 'Name of the System', 'Review Criterion', 'Run'])
CoT_OS_ES_4point1 = CoT_OS_ES_4point1.to_numpy().reshape(20, 1)

CoT_OS_ES_Deepseek = CoT_OS_ES.loc[CoT_OS_ES['LLM'] == 'Deepseek Reasoner']
CoT_OS_ES_Deepseek = CoT_OS_ES_Deepseek.drop(columns=['LLM', 'Prompting Strategies', 'Name of the System', 'Review Criterion', 'Run'])
CoT_OS_ES_Deepseek = CoT_OS_ES_Deepseek.to_numpy().reshape(20, 1)

CoT_OS_ES_Gemini = CoT_OS_ES.loc[CoT_OS_ES['LLM'] == 'Gemini 2.0 Flash']
CoT_OS_ES_Gemini = CoT_OS_ES_Gemini.drop(columns=['LLM', 'Prompting Strategies', 'Name of the System', 'Review Criterion', 'Run'])
CoT_OS_ES_Gemini = CoT_OS_ES_Gemini.to_numpy().reshape(20, 1)
#print(CoT_OS_ES_Gemini)

CoT_OS_ES_aggregate = np.concatenate((CoT_OS_ES_4o, CoT_OS_ES_4point1, CoT_OS_ES_Deepseek, CoT_OS_ES_Gemini), axis = 1)
CoT_OS_ES_aggregate = CoT_OS_ES_aggregate.astype(int)
CoT_OS_ES_aggregate = CoT_OS_ES_aggregate - 1
#Aggregates are subtracted by 1 since aggregate_raters start from 0 and our ratings start at 1

aggregated_CoT_OS_ES, categories = aggregate_raters(CoT_OS_ES_aggregate, n_cat=5)
print(aggregated_CoT_OS_ES)

fleiss_kappa_CoT_OS_ES = fleiss_kappa(aggregated_CoT_OS_ES, method='fleiss')
print("Fleiss Kappa: ", fleiss_kappa_CoT_OS_ES)

[[0 1 3 0 0]
 [0 2 2 0 0]
 [0 2 2 0 0]
 [0 2 2 0 0]
 [0 2 2 0 0]
 [0 0 3 1 0]
 [0 0 3 1 0]
 [0 0 1 3 0]
 [0 0 1 3 0]
 [0 0 2 2 0]
 [0 0 2 2 0]
 [0 0 1 3 0]
 [0 0 2 2 0]
 [0 0 1 3 0]
 [0 0 2 2 0]
 [0 1 2 1 0]
 [0 0 3 1 0]
 [0 0 3 1 0]
 [0 0 2 2 0]
 [0 0 3 1 0]]
Fleiss Kappa:  -0.009239516702203293


CoT One Shot Argument Criticism and Defeat

In [ ]:
CoT_OS_AC_Defeat = ArgumentCriticism.loc[ArgumentCriticism['Prompting Strategies'] == 'CoT One Shot']
#print(CoT_OS_AC_Defeat)


CoT_OS_AC_Defeat_4o = CoT_OS_AC_Defeat.loc[CoT_OS_AC_Defeat['LLM'] == 'GPT4o']
CoT_OS_AC_Defeat_4o = CoT_OS_AC_Defeat_4o.drop(columns=['LLM', 'Prompting Strategies', 'Name of the System', 'Review Criterion', 'Run'])
CoT_OS_AC_Defeat_4o = CoT_OS_AC_Defeat_4o.to_numpy().reshape(20, 1)
#print(CoT_OS_AC_Defeat_4o)

CoT_OS_AC_Defeat_4point1 = CoT_OS_AC_Defeat.loc[CoT_OS_AC_Defeat['LLM'] == 'GPT4.1']
CoT_OS_AC_Defeat_4point1 = CoT_OS_AC_Defeat_4point1.drop(columns=['LLM', 'Prompting Strategies', 'Name of the System', 'Review Criterion', 'Run'])
CoT_OS_AC_Defeat_4point1 = CoT_OS_AC_Defeat_4point1.to_numpy().reshape(20, 1)

CoT_OS_AC_Defeat_Deepseek = CoT_OS_AC_Defeat.loc[CoT_OS_AC_Defeat['LLM'] == 'Deepseek Reasoner']
CoT_OS_AC_Defeat_Deepseek = CoT_OS_AC_Defeat_Deepseek.drop(columns=['LLM', 'Prompting Strategies', 'Name of the System', 'Review Criterion', 'Run'])
CoT_OS_AC_Defeat_Deepseek = CoT_OS_AC_Defeat_Deepseek.to_numpy().reshape(20, 1)
#print(CoT_OS_AC_Defeat_Deepseek)

CoT_OS_AC_Defeat_Gemini = CoT_OS_AC_Defeat.loc[CoT_OS_AC_Defeat['LLM'] == 'Gemini 2.0 Flash']
CoT_OS_AC_Defeat_Gemini = CoT_OS_AC_Defeat_Gemini.drop(columns=['LLM', 'Prompting Strategies', 'Name of the System', 'Review Criterion', 'Run'])
CoT_OS_AC_Defeat_Gemini = CoT_OS_AC_Defeat_Gemini.to_numpy().reshape(20, 1)

CoT_OS_AC_Defeat_aggregate = np.concatenate((CoT_OS_AC_Defeat_4o, CoT_OS_AC_Defeat_4point1, CoT_OS_AC_Defeat_Deepseek, CoT_OS_AC_Defeat_Gemini), axis = 1)
CoT_OS_AC_Defeat_aggregate = CoT_OS_AC_Defeat_aggregate.astype(int)
CoT_OS_AC_Defeat_aggregate = CoT_OS_AC_Defeat_aggregate - 1
#Aggregates are subtracted by 1 since aggregate_raters start from 0 and our ratings start at 1

aggregated_CoT_OS_AC_Defeat, categories = aggregate_raters(CoT_OS_AC_Defeat_aggregate, n_cat=5)
print(aggregated_CoT_OS_AC_Defeat)

fleiss_kappa_CoT_OS_AC_Defeat = fleiss_kappa(aggregated_CoT_OS_AC_Defeat, method='fleiss')
print("Fleiss Kappa: ", fleiss_kappa_CoT_OS_AC_Defeat)

[[0 3 1 0 0]
 [0 2 2 0 0]
 [0 3 1 0 0]
 [0 2 2 0 0]
 [0 2 2 0 0]
 [0 0 3 1 0]
 [0 0 2 2 0]
 [0 0 3 1 0]
 [0 0 2 2 0]
 [0 0 2 2 0]
 [0 0 2 2 0]
 [0 0 1 3 0]
 [0 0 2 2 0]
 [0 0 1 3 0]
 [0 0 1 3 0]
 [0 0 4 0 0]
 [0 0 2 2 0]
 [0 0 4 0 0]
 [0 0 3 1 0]
 [0 0 4 0 0]]
Fleiss Kappa:  0.14529914529914525
